version: "3.9"

services:
  flask:
    container_name: flask
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/backend"
    ports:
      - 5000:5000
    env_file:
      - backend/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
